import { configureStore } from "@reduxjs/toolkit";

import counterReducer from "./counterSlice";
import authReducer from "./authSlice";

// Using redux toolkit
const store = configureStore({
  reducer: { counter: counterReducer, auth: authReducer },
});

// These actions are automatically generated by redux toolkit

export default store;
