import { useDispatch } from "react-redux";
import classes from "./CartButton.module.css";

import { uiActions } from "../../store/uiSlice";

const CartButton = props => {
  const dispatch = useDispatch();

  const toggleCartHandler = () => {
    // toggle() is an action creator automatically generated by createSlice(), and when executed, returns an action object with a type property and a payload property.
    dispatch(uiActions.toggle());
  };
  return (
    <button className={classes.button} onClick={toggleCartHandler}>
      <span>My Cart</span>
      <span className={classes.badge}>1</span>
    </button>
  );
};

export default CartButton;
