import { useDispatch, useSelector } from "react-redux";
import classes from "./CartButton.module.css";

import { uiActions } from "../../store/uiSlice";

const CartButton = props => {
  const dispatch = useDispatch();

  // cart is a key in the reducer object in src/store/index.js, and totalQuantity is a key in the state object in src/store/cartSlice.js.
  const cartQuantity = useSelector(state => state.cart.totalQuantity);

  const toggleCartHandler = () => {
    // toggle() is an action creator automatically generated by createSlice(), and when executed, returns an action object with a type property and a payload property.
    dispatch(uiActions.toggle());
  };
  return (
    <button className={classes.button} onClick={toggleCartHandler}>
      <span>My Cart</span>
      <span className={classes.badge}>{cartQuantity}</span>
    </button>
  );
};

export default CartButton;
